-- Seed dc_entries with defensive coordinators for 2016-2025 (all 32 teams).
-- Generated from src/lib/dcData.js DC_DATA — keep the two in sync by
-- regenerating this file rather than editing rows by hand.
-- Requires docs/migrations/dc_entries_schema.sql. Paste into the Supabase
-- SQL editor. Idempotent: re-running updates existing rows in place.

insert into dc_entries (season, team, name, partial, playcaller, note) values
  (2016, '__init__', '', false, null, null),
  (2017, '__init__', '', false, null, null),
  (2018, '__init__', '', false, null, null),
  (2019, '__init__', '', false, null, null),
  (2020, '__init__', '', false, null, null),
  (2021, '__init__', '', false, null, null),
  (2022, '__init__', '', false, null, null),
  (2023, '__init__', '', false, null, null),
  (2024, '__init__', '', false, null, null),
  (2025, '__init__', '', false, null, null),
  (2016, 'ARI', 'James Bettcher', false, null, null),
  (2016, 'ATL', 'Richard Smith', false, null, null),
  (2016, 'BAL', 'Dean Pees', false, null, null),
  (2016, 'BUF', 'Dennis Thurman', false, null, null),
  (2016, 'CAR', 'Sean McDermott', false, null, null),
  (2016, 'CHI', 'Vic Fangio', false, null, null),
  (2016, 'CIN', 'Paul Guenther', false, null, null),
  (2016, 'CLE', 'Ray Horton', false, null, null),
  (2016, 'DAL', 'Rod Marinelli', false, null, null),
  (2016, 'DEN', 'Wade Phillips', false, null, null),
  (2016, 'DET', 'Teryl Austin', false, null, null),
  (2016, 'GB', 'Dom Capers', false, null, null),
  (2016, 'HOU', 'Romeo Crennel', false, null, null),
  (2016, 'IND', 'Ted Monachino', false, null, null),
  (2016, 'JAX', 'Todd Wash', false, null, null),
  (2016, 'KC', 'Bob Sutton', false, null, null),
  (2016, 'LAC', 'John Pagano', false, null, null),
  (2016, 'LAR', 'Gregg Williams', false, null, null),
  (2016, 'LV', 'Ken Norton Jr.', false, null, null),
  (2016, 'MIA', 'Vance Joseph', false, null, null),
  (2016, 'MIN', 'George Edwards', false, 'HC', 'HC Mike Zimmer called plays.'),
  (2016, 'NE', 'Matt Patricia', false, null, null),
  (2016, 'NO', 'Dennis Allen', false, null, null),
  (2016, 'NYG', 'Steve Spagnuolo', false, null, null),
  (2016, 'NYJ', 'Kacy Rodgers', false, null, null),
  (2016, 'PHI', 'Jim Schwartz', false, null, null),
  (2016, 'PIT', 'Keith Butler', false, null, null),
  (2016, 'SEA', 'Kris Richard', false, null, null),
  (2016, 'SF', 'Jim O''Neil', false, null, null),
  (2016, 'TB', 'Mike Smith', false, null, null),
  (2016, 'TEN', 'Dick LeBeau', false, null, null),
  (2016, 'WAS', 'Joe Barry', false, null, null),
  (2017, 'ARI', 'James Bettcher', false, null, null),
  (2017, 'ATL', 'Marquand Manuel', false, null, null),
  (2017, 'BAL', 'Dean Pees', false, null, null),
  (2017, 'BUF', 'Leslie Frazier', false, null, null),
  (2017, 'CAR', 'Steve Wilks', false, null, null),
  (2017, 'CHI', 'Vic Fangio', false, null, null),
  (2017, 'CIN', 'Paul Guenther', false, null, null),
  (2017, 'CLE', 'Gregg Williams', false, null, null),
  (2017, 'DAL', 'Rod Marinelli', false, null, null),
  (2017, 'DEN', 'Joe Woods', false, null, null),
  (2017, 'DET', 'Teryl Austin', false, null, null),
  (2017, 'GB', 'Dom Capers', false, null, null),
  (2017, 'HOU', 'Mike Vrabel', false, null, null),
  (2017, 'IND', 'Ted Monachino', false, null, null),
  (2017, 'JAX', 'Todd Wash', false, null, null),
  (2017, 'KC', 'Bob Sutton', false, null, null),
  (2017, 'LAC', 'Gus Bradley', false, null, null),
  (2017, 'LAR', 'Wade Phillips', false, null, null),
  (2017, 'LV', 'Ken Norton Jr.', true, null, 'Fired late season; John Pagano finished.'),
  (2017, 'MIA', 'Matt Burke', false, null, null),
  (2017, 'MIN', 'George Edwards', false, 'HC', 'HC Mike Zimmer called plays.'),
  (2017, 'NE', 'Matt Patricia', false, null, null),
  (2017, 'NO', 'Dennis Allen', false, null, null),
  (2017, 'NYG', 'Steve Spagnuolo', false, null, null),
  (2017, 'NYJ', 'Kacy Rodgers', false, null, null),
  (2017, 'PHI', 'Jim Schwartz', false, null, null),
  (2017, 'PIT', 'Keith Butler', false, null, null),
  (2017, 'SEA', 'Kris Richard', false, null, null),
  (2017, 'SF', 'Robert Saleh', false, null, null),
  (2017, 'TB', 'Mike Smith', false, null, null),
  (2017, 'TEN', 'Dick LeBeau', false, null, null),
  (2017, 'WAS', 'Greg Manusky', false, null, null),
  (2018, 'ARI', 'Al Holcomb', false, null, null),
  (2018, 'ATL', 'Marquand Manuel', false, null, null),
  (2018, 'BAL', 'Don Martindale', false, null, null),
  (2018, 'BUF', 'Leslie Frazier', false, null, null),
  (2018, 'CAR', 'Eric Washington', false, null, null),
  (2018, 'CHI', 'Vic Fangio', false, null, null),
  (2018, 'CIN', 'Teryl Austin', false, null, null),
  (2018, 'CLE', 'Gregg Williams', false, null, null),
  (2018, 'DAL', 'Rod Marinelli', false, null, 'Kris Richard called the passing game.'),
  (2018, 'DEN', 'Joe Woods', false, null, null),
  (2018, 'DET', 'Paul Pasqualoni', false, null, null),
  (2018, 'GB', 'Mike Pettine', false, null, null),
  (2018, 'HOU', 'Romeo Crennel', false, null, null),
  (2018, 'IND', 'Matt Eberflus', false, null, null),
  (2018, 'JAX', 'Todd Wash', false, null, null),
  (2018, 'KC', 'Bob Sutton', false, null, null),
  (2018, 'LAC', 'Gus Bradley', false, null, null),
  (2018, 'LAR', 'Wade Phillips', false, null, null),
  (2018, 'LV', 'Paul Guenther', false, null, null),
  (2018, 'MIA', 'Matt Burke', false, null, null),
  (2018, 'MIN', 'George Edwards', false, 'HC', 'HC Mike Zimmer called plays.'),
  (2018, 'NE', 'Brian Flores', false, 'HC', 'LBs coach ran the calls; Bill Belichick de facto controlled the defense.'),
  (2018, 'NO', 'Dennis Allen', false, null, null),
  (2018, 'NYG', 'James Bettcher', false, null, null),
  (2018, 'NYJ', 'Kacy Rodgers', false, null, null),
  (2018, 'PHI', 'Jim Schwartz', false, null, null),
  (2018, 'PIT', 'Keith Butler', false, null, null),
  (2018, 'SEA', 'Ken Norton Jr.', false, null, null),
  (2018, 'SF', 'Robert Saleh', false, null, null),
  (2018, 'TB', 'Mike Smith', true, null, 'Fired mid-season; Mark Duffner finished.'),
  (2018, 'TEN', 'Dean Pees', false, null, null),
  (2018, 'WAS', 'Greg Manusky', false, null, null),
  (2019, 'ARI', 'Vance Joseph', false, null, null),
  (2019, 'ATL', 'Dan Quinn', false, 'HC', 'HC ran the defense; Jeff Ulbrich handled the front.'),
  (2019, 'BAL', 'Don Martindale', false, null, null),
  (2019, 'BUF', 'Leslie Frazier', false, null, null),
  (2019, 'CAR', 'Eric Washington', false, null, null),
  (2019, 'CHI', 'Chuck Pagano', false, null, null),
  (2019, 'CIN', 'Lou Anarumo', false, null, null),
  (2019, 'CLE', 'Steve Wilks', false, null, null),
  (2019, 'DAL', 'Rod Marinelli', false, null, 'Kris Richard called the passing game.'),
  (2019, 'DEN', 'Ed Donatell', false, null, null),
  (2019, 'DET', 'Paul Pasqualoni', false, null, null),
  (2019, 'GB', 'Mike Pettine', false, null, null),
  (2019, 'HOU', 'Romeo Crennel', false, null, null),
  (2019, 'IND', 'Matt Eberflus', false, null, null),
  (2019, 'JAX', 'Todd Wash', false, null, null),
  (2019, 'KC', 'Steve Spagnuolo', false, null, null),
  (2019, 'LAC', 'Gus Bradley', false, null, null),
  (2019, 'LAR', 'Wade Phillips', false, null, null),
  (2019, 'LV', 'Paul Guenther', false, null, null),
  (2019, 'MIA', 'Patrick Graham', false, null, null),
  (2019, 'MIN', 'George Edwards', false, 'HC', 'HC Mike Zimmer called plays.'),
  (2019, 'NE', 'Jerod Mayo / Steve Belichick', false, 'HC', 'No formal DC; Bill Belichick called plays.'),
  (2019, 'NO', 'Dennis Allen', false, null, null),
  (2019, 'NYG', 'James Bettcher', false, null, null),
  (2019, 'NYJ', 'Gregg Williams', false, null, null),
  (2019, 'PHI', 'Jim Schwartz', false, null, null),
  (2019, 'PIT', 'Keith Butler', false, null, null),
  (2019, 'SEA', 'Ken Norton Jr.', false, null, null),
  (2019, 'SF', 'Robert Saleh', false, null, null),
  (2019, 'TB', 'Todd Bowles', false, null, null),
  (2019, 'TEN', 'Dean Pees', false, null, null),
  (2019, 'WAS', 'Greg Manusky', false, null, null),
  (2020, 'ARI', 'Vance Joseph', false, null, null),
  (2020, 'ATL', 'Jeff Ulbrich', false, null, null),
  (2020, 'BAL', 'Don Martindale', false, null, null),
  (2020, 'BUF', 'Leslie Frazier', false, null, null),
  (2020, 'CAR', 'Phil Snow', false, null, null),
  (2020, 'CHI', 'Chuck Pagano', false, null, null),
  (2020, 'CIN', 'Lou Anarumo', false, null, null),
  (2020, 'CLE', 'Joe Woods', false, null, null),
  (2020, 'DAL', 'Mike Nolan', false, null, null),
  (2020, 'DEN', 'Ed Donatell', false, null, null),
  (2020, 'DET', 'Cory Undlin', false, null, null),
  (2020, 'GB', 'Mike Pettine', false, null, null),
  (2020, 'HOU', 'Anthony Weaver', false, null, null),
  (2020, 'IND', 'Matt Eberflus', false, null, null),
  (2020, 'JAX', 'Todd Wash', false, null, null),
  (2020, 'KC', 'Steve Spagnuolo', false, null, null),
  (2020, 'LAC', 'Gus Bradley', false, null, null),
  (2020, 'LAR', 'Brandon Staley', false, null, null),
  (2020, 'LV', 'Paul Guenther', false, null, null),
  (2020, 'MIA', 'Josh Boyer', false, null, null),
  (2020, 'MIN', 'Andre Patterson / Adam Zimmer', false, 'HC', 'Co-DCs; HC Mike Zimmer called plays.'),
  (2020, 'NE', 'Jerod Mayo / Steve Belichick', false, 'HC', 'No formal DC; Bill Belichick called plays.'),
  (2020, 'NO', 'Dennis Allen', false, null, null),
  (2020, 'NYG', 'Patrick Graham', false, null, null),
  (2020, 'NYJ', 'Gregg Williams', false, null, null),
  (2020, 'PHI', 'Jim Schwartz', false, null, null),
  (2020, 'PIT', 'Keith Butler', false, null, null),
  (2020, 'SEA', 'Ken Norton Jr.', false, null, null),
  (2020, 'SF', 'Robert Saleh', false, null, null),
  (2020, 'TB', 'Todd Bowles', false, null, null),
  (2020, 'TEN', 'Dean Pees', false, null, null),
  (2020, 'WAS', 'Jack Del Rio', false, null, null),
  (2021, 'ARI', 'Vance Joseph', false, null, null),
  (2021, 'ATL', 'Dean Pees', false, null, null),
  (2021, 'BAL', 'Don Martindale', false, null, null),
  (2021, 'BUF', 'Leslie Frazier', false, null, null),
  (2021, 'CAR', 'Phil Snow', false, null, null),
  (2021, 'CHI', 'Sean Desai', false, null, null),
  (2021, 'CIN', 'Lou Anarumo', false, null, null),
  (2021, 'CLE', 'Joe Woods', false, null, null),
  (2021, 'DAL', 'Dan Quinn', false, null, null),
  (2021, 'DEN', 'Ed Donatell', false, null, null),
  (2021, 'DET', 'Aaron Glenn', false, null, null),
  (2021, 'GB', 'Joe Barry', false, null, null),
  (2021, 'HOU', 'Lovie Smith', false, null, null),
  (2021, 'IND', 'Matt Eberflus', false, null, null),
  (2021, 'JAX', 'Joe Cullen', false, null, null),
  (2021, 'KC', 'Steve Spagnuolo', false, null, null),
  (2021, 'LAC', 'Renaldo Hill', false, null, null),
  (2021, 'LAR', 'Raheem Morris', false, null, null),
  (2021, 'LV', 'Gus Bradley', false, null, null),
  (2021, 'MIA', 'Josh Boyer', false, null, null),
  (2021, 'MIN', 'Andre Patterson / Adam Zimmer', false, 'HC', 'Co-DCs; HC Mike Zimmer called plays.'),
  (2021, 'NE', 'Jerod Mayo / Steve Belichick', false, 'HC', 'No formal DC; Bill Belichick called plays.'),
  (2021, 'NO', 'Dennis Allen', false, null, null),
  (2021, 'NYG', 'Patrick Graham', false, null, null),
  (2021, 'NYJ', 'Jeff Ulbrich', false, null, null),
  (2021, 'PHI', 'Jonathan Gannon', false, null, null),
  (2021, 'PIT', 'Keith Butler', false, null, null),
  (2021, 'SEA', 'Ken Norton Jr.', false, null, null),
  (2021, 'SF', 'DeMeco Ryans', false, null, null),
  (2021, 'TB', 'Todd Bowles', false, null, null),
  (2021, 'TEN', 'Shane Bowen', false, null, null),
  (2021, 'WAS', 'Jack Del Rio', false, null, null),
  (2022, 'ARI', 'Vance Joseph', false, null, null),
  (2022, 'ATL', 'Dean Pees', false, null, null),
  (2022, 'BAL', 'Mike Macdonald', false, null, null),
  (2022, 'BUF', 'Leslie Frazier', false, null, null),
  (2022, 'CAR', 'Phil Snow', false, null, null),
  (2022, 'CHI', 'Alan Williams', false, null, null),
  (2022, 'CIN', 'Lou Anarumo', false, null, null),
  (2022, 'CLE', 'Joe Woods', false, null, null),
  (2022, 'DAL', 'Dan Quinn', false, null, null),
  (2022, 'DEN', 'Ejiro Evero', false, null, null),
  (2022, 'DET', 'Aaron Glenn', false, null, null),
  (2022, 'GB', 'Joe Barry', false, null, null),
  (2022, 'HOU', 'Lovie Smith', false, 'HC', 'HC called the defense himself.'),
  (2022, 'IND', 'Gus Bradley', false, null, null),
  (2022, 'JAX', 'Mike Caldwell', false, null, null),
  (2022, 'KC', 'Steve Spagnuolo', false, null, null),
  (2022, 'LAC', 'Renaldo Hill', false, null, null),
  (2022, 'LAR', 'Raheem Morris', false, null, null),
  (2022, 'LV', 'Patrick Graham', false, null, null),
  (2022, 'MIA', 'Josh Boyer', false, null, null),
  (2022, 'MIN', 'Ed Donatell', false, null, null),
  (2022, 'NE', 'Jerod Mayo / Steve Belichick', false, 'HC', 'No formal DC; Bill Belichick called plays.'),
  (2022, 'NO', 'Ryan Nielsen / Kris Richard', false, 'HC', 'Co-DCs; HC Dennis Allen called plays.'),
  (2022, 'NYG', 'Don Martindale', false, null, null),
  (2022, 'NYJ', 'Jeff Ulbrich', false, null, null),
  (2022, 'PHI', 'Jonathan Gannon', false, null, null),
  (2022, 'PIT', 'Teryl Austin', false, null, null),
  (2022, 'SEA', 'Clint Hurtt', false, null, null),
  (2022, 'SF', 'DeMeco Ryans', false, null, null),
  (2022, 'TB', 'Todd Bowles', false, 'HC', 'Promoted to HC; kept defensive play-calling.'),
  (2022, 'TEN', 'Shane Bowen', false, null, null),
  (2022, 'WAS', 'Jack Del Rio', false, null, null),
  (2023, 'ARI', 'Nick Rallis', false, null, null),
  (2023, 'ATL', 'Ryan Nielsen', false, null, null),
  (2023, 'BAL', 'Mike Macdonald', false, null, null),
  (2023, 'BUF', 'Sean McDermott', false, 'HC', 'HC called plays after Leslie Frazier stepped aside; no formal DC.'),
  (2023, 'CAR', 'Ejiro Evero', false, null, null),
  (2023, 'CHI', 'Alan Williams', true, 'HC', 'Resigned early season; HC Matt Eberflus took over play-calling.'),
  (2023, 'CIN', 'Lou Anarumo', false, null, null),
  (2023, 'CLE', 'Jim Schwartz', false, null, null),
  (2023, 'DAL', 'Dan Quinn', false, null, null),
  (2023, 'DEN', 'Vance Joseph', false, null, null),
  (2023, 'DET', 'Aaron Glenn', false, null, null),
  (2023, 'GB', 'Joe Barry', false, null, null),
  (2023, 'HOU', 'Matt Burke', false, 'HC', 'HC DeMeco Ryans calls the defense.'),
  (2023, 'IND', 'Gus Bradley', false, null, null),
  (2023, 'JAX', 'Mike Caldwell', false, null, null),
  (2023, 'KC', 'Steve Spagnuolo', false, null, null),
  (2023, 'LAC', 'Derrick Ansley', false, null, null),
  (2023, 'LAR', 'Raheem Morris', false, null, null),
  (2023, 'LV', 'Patrick Graham', false, null, null),
  (2023, 'MIA', 'Vic Fangio', false, null, null),
  (2023, 'MIN', 'Brian Flores', false, null, null),
  (2023, 'NE', 'Jerod Mayo / Steve Belichick', false, 'HC', 'No formal DC; Bill Belichick called plays.'),
  (2023, 'NO', 'Joe Woods', false, 'HC', 'HC Dennis Allen called plays.'),
  (2023, 'NYG', 'Don Martindale', false, null, null),
  (2023, 'NYJ', 'Jeff Ulbrich', false, null, null),
  (2023, 'PHI', 'Sean Desai', true, null, 'Demoted late season; Matt Patricia took over calls.'),
  (2023, 'PIT', 'Teryl Austin', false, null, null),
  (2023, 'SEA', 'Clint Hurtt', false, null, null),
  (2023, 'SF', 'Steve Wilks', false, null, null),
  (2023, 'TB', 'Todd Bowles', false, 'HC', 'HC kept defensive play-calling.'),
  (2023, 'TEN', 'Shane Bowen', false, null, null),
  (2023, 'WAS', 'Jack Del Rio', true, null, 'Fired late season; HC Ron Rivera took over calls.'),
  (2024, 'ARI', 'Nick Rallis', false, null, null),
  (2024, 'ATL', 'Jimmy Lake', false, null, null),
  (2024, 'BAL', 'Zach Orr', false, null, null),
  (2024, 'BUF', 'Bobby Babich', false, null, null),
  (2024, 'CAR', 'Ejiro Evero', false, null, null),
  (2024, 'CHI', 'Eric Washington', false, 'HC', 'HC Matt Eberflus called plays.'),
  (2024, 'CIN', 'Lou Anarumo', false, null, null),
  (2024, 'CLE', 'Jim Schwartz', false, null, null),
  (2024, 'DAL', 'Mike Zimmer', false, null, null),
  (2024, 'DEN', 'Vance Joseph', false, null, null),
  (2024, 'DET', 'Aaron Glenn', false, null, null),
  (2024, 'GB', 'Jeff Hafley', false, null, null),
  (2024, 'HOU', 'Matt Burke', false, 'HC', 'HC DeMeco Ryans calls the defense.'),
  (2024, 'IND', 'Gus Bradley', false, null, null),
  (2024, 'JAX', 'Ryan Nielsen', false, null, null),
  (2024, 'KC', 'Steve Spagnuolo', false, null, null),
  (2024, 'LAC', 'Jesse Minter', false, null, null),
  (2024, 'LAR', 'Chris Shula', false, null, null),
  (2024, 'LV', 'Patrick Graham', false, null, null),
  (2024, 'MIA', 'Anthony Weaver', false, null, null),
  (2024, 'MIN', 'Brian Flores', false, null, null),
  (2024, 'NE', 'DeMarcus Covington', false, null, null),
  (2024, 'NO', 'Joe Woods', false, 'HC', 'HC Dennis Allen called plays until his mid-season firing.'),
  (2024, 'NYG', 'Shane Bowen', false, null, null),
  (2024, 'NYJ', 'Jeff Ulbrich', false, null, 'Became interim HC after Saleh firing; kept the defense.'),
  (2024, 'PHI', 'Vic Fangio', false, null, null),
  (2024, 'PIT', 'Teryl Austin', false, null, null),
  (2024, 'SEA', 'Aden Durde', false, 'HC', 'HC Mike Macdonald calls the defense.'),
  (2024, 'SF', 'Nick Sorensen', false, null, null),
  (2024, 'TB', 'Todd Bowles', false, 'HC', 'HC kept defensive play-calling.'),
  (2024, 'TEN', 'Dennard Wilson', false, null, null),
  (2024, 'WAS', 'Joe Whitt Jr.', false, null, null),
  (2025, 'ARI', 'Nick Rallis', false, null, null),
  (2025, 'ATL', 'Jeff Ulbrich', false, null, null),
  (2025, 'BAL', 'Zach Orr', false, null, null),
  (2025, 'BUF', 'Bobby Babich', false, null, null),
  (2025, 'CAR', 'Ejiro Evero', false, null, null),
  (2025, 'CHI', 'Dennis Allen', false, null, null),
  (2025, 'CIN', 'Al Golden', false, null, null),
  (2025, 'CLE', 'Jim Schwartz', false, null, null),
  (2025, 'DAL', 'Matt Eberflus', false, null, null),
  (2025, 'DEN', 'Vance Joseph', false, null, null),
  (2025, 'DET', 'Kelvin Sheppard', false, null, null),
  (2025, 'GB', 'Jeff Hafley', false, null, null),
  (2025, 'HOU', 'Matt Burke', false, 'HC', 'HC DeMeco Ryans calls the defense.'),
  (2025, 'IND', 'Lou Anarumo', false, null, null),
  (2025, 'JAX', 'Anthony Campanile', false, null, null),
  (2025, 'KC', 'Steve Spagnuolo', false, null, null),
  (2025, 'LAC', 'Jesse Minter', false, null, null),
  (2025, 'LAR', 'Chris Shula', false, null, null),
  (2025, 'LV', 'Patrick Graham', false, null, null),
  (2025, 'MIA', 'Anthony Weaver', false, null, null),
  (2025, 'MIN', 'Brian Flores', false, null, null),
  (2025, 'NE', 'DeMarcus Covington', false, null, null),
  (2025, 'NO', 'Brandon Staley', false, null, null),
  (2025, 'NYG', 'Shane Bowen', false, null, null),
  (2025, 'NYJ', 'Aaron Glenn', false, 'HC', 'New HC runs the defensive structure.'),
  (2025, 'PHI', 'Vic Fangio', false, null, null),
  (2025, 'PIT', 'Teryl Austin', false, null, null),
  (2025, 'SEA', 'Aden Durde', false, 'HC', 'HC Mike Macdonald calls the defense.'),
  (2025, 'SF', 'Nick Sorensen', false, null, null),
  (2025, 'TB', 'Todd Bowles', false, 'HC', 'HC kept defensive play-calling.'),
  (2025, 'TEN', 'Dennard Wilson', false, null, null),
  (2025, 'WAS', 'Joe Whitt Jr.', false, null, null)
on conflict (season, team) do update set
  name       = excluded.name,
  partial    = excluded.partial,
  playcaller = excluded.playcaller,
  note       = excluded.note,
  updated_at = now();
