-- dc_entries: Supabase override layer for the DC dataset (dcData.js) — the DC
-- twin of oc_entries. The DC Manager tab in /admin/idp-matchups writes from
-- the browser using the anon key (auth is gated client-side, same pattern as
-- the OC editor), so read + write stay open to anon. Paste into the Supabase
-- SQL editor — or it may already be applied via the MCP migration
-- `dc_entries_schema`.

create table if not exists dc_entries (
  id         bigint generated by default as identity primary key,
  season     integer not null,
  team       text not null,
  name       text not null,
  partial    boolean not null default false,
  playcaller text,
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season, team)
);

alter table dc_entries enable row level security;

drop policy if exists dc_entries_read   on dc_entries;
drop policy if exists dc_entries_insert on dc_entries;
drop policy if exists dc_entries_update on dc_entries;
drop policy if exists dc_entries_delete on dc_entries;

create policy dc_entries_read
  on dc_entries for select
  using (true);

create policy dc_entries_insert
  on dc_entries for insert
  with check (true);

create policy dc_entries_update
  on dc_entries for update
  using (true) with check (true);

create policy dc_entries_delete
  on dc_entries for delete
  using (true);
