export const styles = {
  app: {
    minHeight: "100vh",
    background: "#141722",
    color: "#e8e8f0",
    position: "relative",
    overflow: "hidden",
  },
  grid: {
    position: "fixed",
    inset: 0,
    backgroundImage:
      "linear-gradient(rgba(0,245,160,0.045) 1px, transparent 1px), linear-gradient(90deg, rgba(0,245,160,0.045) 1px, transparent 1px)",
    backgroundSize: "40px 40px",
    pointerEvents: "none",
    zIndex: 0,
  },
  content: {
    position: "relative",
    zIndex: 1,
    maxWidth: 960,
    margin: "0 auto",
    padding: "48px 24px 80px",
  },
  header: {
    marginBottom: 36,
    borderBottom: "1px solid rgba(0,245,160,0.15)",
    paddingBottom: 24,
  },
  logo: {
    fontSize: 10,
    letterSpacing: 5,
    color: "#00f5a0",
    textTransform: "uppercase",
    marginBottom: 10,
    opacity: 0.6,
  },
  title: {
    fontSize: 28,
    fontWeight: 700,
    color: "#fff",
    letterSpacing: -0.5,
    lineHeight: 1.2,
  },
  subtitle: {
    fontSize: 12,
    color: "#d7dcef",
    marginTop: 6,
    letterSpacing: 0.5,
  },
  input: {
    background: "rgba(0,245,160,0.04)",
    border: "1px solid rgba(0,245,160,0.18)",
    color: "#e8e8f0",
    padding: "13px 18px",
    fontSize: 15,
    width: "100%",
    borderRadius: 3,
    transition: "border-color 0.15s, box-shadow 0.15s",
  },
  btn: {
    background: "#00f5a0",
    color: "#050508",
    border: "none",
    padding: "13px 28px",
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 2.5,
    textTransform: "uppercase",
    borderRadius: 3,
  },
  btnOutline: {
    background: "transparent",
    color: "#00f5a0",
    border: "1px solid rgba(0,245,160,0.3)",
    padding: "12px 18px",
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    borderRadius: 3,
    width: "100%",
    textAlign: "left",
    marginBottom: 6,
  },
  btnGhost: {
    background: "transparent",
    color: "#eef1ff",
    border: "1px solid rgba(255,255,255,0.24)",
    padding: "7px 14px",
    fontSize: 10,
    letterSpacing: 2,
    textTransform: "uppercase",
    borderRadius: 3,
  },
  card: {
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.15)",
    padding: "18px 22px",
    borderRadius: 5,
    marginBottom: 12,
  },
  tag: (color) => ({
    display: "inline-block",
    padding: "3px 9px",
    borderRadius: 2,
    fontSize: 9,
    letterSpacing: 1.5,
    fontWeight: 700,
    textTransform: "uppercase",
    background: `${color}1a`,
    color,
    border: `1px solid ${color}40`,
    whiteSpace: "nowrap",
  }),
  tab: (active) => ({
    padding: "10px 18px",
    fontSize: 10,
    letterSpacing: 2,
    textTransform: "uppercase",
    border: "none",
    background: "transparent",
    color: active ? "#00f5a0" : "#c3c9dd",
    borderBottom: active ? "2px solid #00f5a0" : "2px solid transparent",
  }),
  playerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 0",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
  },
  sectionLabel: {
    fontSize: 9,
    letterSpacing: 3.5,
    color: "#00f5a0",
    textTransform: "uppercase",
    marginBottom: 14,
    opacity: 0.75,
  },
};
